services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: wppipe-api
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: wppipe-client
    ports:
      - "3000:80"
  triton_server:
    build:
      context: .
      dockerfile: Dockerfile.triton
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command:
          - tritonserver
          - --model-repository=/models
          - --strict-model-config=false
          - --log-verbose=1
